course/urls.py
from django.urls import path
from course import views

urlpatterns = [
    path('course_list/', views.course_list, name='course_list'),
    path('course/<int:pk>/', views.course_detail, name='course_detail'),
    path('my_course/', views.my_course, name='my_course'),
    path('course/<int:pk>/edit/', views.course_edit, name='course_edit'),
    path('course_new/', views.course_new, name='course_new'),
    path('course/<int:pk>/record', views.record_to_course, name='record_to_course'),
    path('course_list/search/', views.search),
]

courses/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from courses import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from courses import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('course.urls')),
    path('', views.index),
    path('account/', include('profile.urls')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)

course/models.py
from django.db import models
from django.utils import timezone
from django.core.validators import MinValueValidator, MaxValueValidator
from django.contrib.auth.models import User
from .validators import validate_file_extension
from django.contrib.auth.models import Group, Permission, User


class Course(models.Model):
    title = models.CharField(max_length=128, verbose_name='Название', unique=True)
    description = models.TextField(verbose_name='Описание')
    price = models.PositiveIntegerField(validators=[MinValueValidator(0)], verbose_name='Цена')
    start_date = models.DateField(verbose_name='Начало курса')
    duration = models.PositiveIntegerField(validators=[MinValueValidator(0)], verbose_name='Колличество занятий')
    lesson_duration = models.PositiveIntegerField(blank=True, null=True,
                                                  validators=[MinValueValidator(0), MaxValueValidator(24)],
                                                  verbose_name='Продолжительность одного занятия(час)')
    image = models.ImageField(blank=True, null=True, upload_to='course_images', default='course_images/default.png',
                              verbose_name='Обложка')
    contract = models.FileField(blank=True, null=True, upload_to="documents/contract", verbose_name='Договор')
    invoice = models.FileField(blank=True, null=True, upload_to="documents/invoice", verbose_name='Квитанция')
    work_program = models.FileField(blank=True, null=True, upload_to="documents/work_program",
                                    verbose_name='Рабочая программа')
    lecturer = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Преподователь')

    class Meta:
        verbose_name = 'Курс'
        verbose_name_plural = 'Курсы'
        ordering = ['-id']
        permissions = (
            ("student", "Студент"),
            ("lecturer", "Преподователь")
        )

    def publish(self):
        self.start_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title


class Institute(models.Model):
    title = models.CharField(max_length=64, verbose_name='Название')

    class Meta:
        verbose_name = 'Институт'
        verbose_name_plural = 'Институты'

    def __str__(self):
        return self.title


class Department(models.Model):
    title = models.CharField(max_length=64, verbose_name='Название')
    institute = models.ForeignKey(Institute, on_delete=models.CASCADE, verbose_name='Институт', null=True)

    class Meta:
        verbose_name = 'Кафедра'
        verbose_name_plural = 'Кафедры'

    def __str__(self):
        return self.title


class StudyGroup(models.Model):
    title = models.CharField(max_length=16, verbose_name='Название')
    department = models.ForeignKey(Department, on_delete=models.CASCADE, verbose_name='Кафедра', null=True)

    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'

    def __str__(self):
        return self.title


class Record(models.Model):
    student = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    name = models.CharField(max_length=64, verbose_name='Имя')
    surname = models.CharField(max_length=64, verbose_name='Фамилия')
    patronymic = models.CharField(max_length=64, null=True, verbose_name='Отчество')
    date_birth = models.DateField(null=True, verbose_name='Дата Рождения')
    phone = models.CharField(max_length=11, null=True, verbose_name='Телефон')
    email = models.EmailField(default='', verbose_name='E-mail')
    institute = models.ForeignKey(Institute, on_delete=models.CASCADE, null=True, blank=True, verbose_name='Институт')
    department = models.ForeignKey(Department, on_delete=models.CASCADE, null=True, blank=True, verbose_name='Кафедра')
    group = models.ForeignKey(StudyGroup, on_delete=models.CASCADE, null=True, blank=True, verbose_name='Группа')
    contract = models.FileField(upload_to="record/documents/contract", validators=[validate_file_extension], null=True,
                                verbose_name='Договор')
    invoice = models.FileField(upload_to="record/documents/invoice", validators=[validate_file_extension], null=True,
                               verbose_name='Квитанция')

    class Meta:
        verbose_name = 'Запись'
        verbose_name_plural = 'Записи'

    def __str__(self):
        return '{} {}({}) записался на курс {}'.format(self.name, self.surname, self.student, self.course)

course/forms.py
from django import forms
from course.models import Course, Record, Institute, Department, StudyGroup


class CourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = (
            'title', 'description', 'price', 'start_date', 'duration', 'lesson_duration', 'contract', 'invoice',
            'image', 'work_program')
        widget = {'contract': forms.FileInput()}

    def __init__(self, *args, **kwargs):
        super(CourseForm, self).__init__(*args, **kwargs)
        self.fields['description'].widget.attrs.update({'class': 'materialize-textarea'})
        self.fields['start_date'].widget.attrs.update({'class': 'datepicker'})


class RecordForm(forms.ModelForm):
    class Meta:
        model = Record
        fields = (
            'name', 'surname', 'patronymic', 'date_birth', 'phone', 'email', 'institute', 'department', 'group',
            'contract', 'invoice')

    def __init__(self, *args, **kwargs):
        super(RecordForm, self).__init__(*args, **kwargs)
        self.fields['date_birth'].widget.attrs.update({'class': 'datepicker'})
        self.fields['institute'].queryset = Institute.objects.all()
        self.fields['department'].queryset = Department.objects.all()
        self.fields['group'].queryset = StudyGroup.objects.all()

course/views.py
from django.shortcuts import render, get_object_or_404, redirect
from course.models import Course, Record
from course.forms import CourseForm, RecordForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def course_list(request):
    courses = Course.objects.all()
    paginator = Paginator(courses, 8)
    page = request.GET.get('page')
    try:
        course = paginator.page(page)
    except PageNotAnInteger:
        course = paginator.page(1)
    except EmptyPage:
        course = paginator.page(paginator.num_pages)
    return render(request, 'course/course_list.html', {'course': course})


def my_course(request):
    student = Record.objects.filter(student__username=request.user)
    my_courses = Course.objects.filter(lecturer__username=request.user)
    paginator = Paginator(my_courses, 8)
    page = request.GET.get('page')
    try:
        my_course = paginator.page(page)
    except PageNotAnInteger:
        my_course = paginator.page(1)
    except EmptyPage:
        my_course = paginator.page(paginator.num_pages)
    return render(request, 'course/my_course.html', {'my_course': my_course})


def course_detail(request, pk):
    course = get_object_or_404(Course, pk=pk)
    records = Record.objects.filter(course=course)
    return render(request, 'course/course_detail.html', {'course': course, 'records': records})


def course_edit(request, pk):
    if request.user.has_perm('course.lecturer'):
        course = get_object_or_404(Course, pk=pk)
        if request.user == course.lecturer:
            if request.method == "POST":
                form = CourseForm(request.POST, request.FILES, instance=course)
                if form.is_valid():
                    course = form.save(commit=False)
                    course.lecturer = request.user
                    course.save()
                    return redirect('course_detail', pk=course.pk)
            else:
                form = CourseForm(instance=course)
            return render(request, 'course/course_edit.html', {'form': form})
        else:
            return redirect('course_detail', pk=course.pk)


def course_new(request):
    if request.user.has_perm('course.lecturer'):
        if request.method == "POST":
            form = CourseForm(request.POST, request.FILES)
            if form.is_valid():
                course = form.save(commit=False)
                course.lecturer = request.user
                course.save()
                return redirect('course_detail', pk=course.pk)
        else:
            form = CourseForm()
        return render(request, 'course/course_edit.html', {'form': form})


def record_to_course(request, pk):
    if request.user.has_perm('course.student'):
        course = get_object_or_404(Course, pk=pk)
        if request.method == "POST":
            form = RecordForm(request.POST, request.FILES)
            if form.is_valid():
                record = form.save(commit=False)
                record.student = request.user
                record.course = course
                record.save()
                return redirect('course_detail', pk=course.pk)
        else:
            form = RecordForm()
        return render(request, 'course/record_to_course.html', {'form': form})


def search(request):
    error = False
    if 'q' in request.GET:
        q = request.GET['q']
        if not q:
            error = True
        else:
            course = Course.objects.filter(title__icontains=q)
            return render(request, 'course/course_list.html', {'course': course})
    return render(request, 'course/course_list.html', {'error': error})

templates/course/course_detail.html
{% extends 'base.html' %}
{% block course %}
    <div class="row">
        <div class="col s12 l6">
            <div class="card disable-card">
                <div class="card-content">
                    <span class="card-title light-text">{{ course.title }}</span>
                    <p>{{ course.description }}</p>
                </div>
                <div class="card-action">
                    {% if request.user == course.lecturer %}
                        <a class="waves-effect waves btn
                            btn-flat blue accent-4 white-text"
                           href="{% url 'course_edit' pk=course.pk %}">Редактировать</a>
                    {% endif %}
                    {% if perms.course.student %}
                        <a class="waves-effect waves btn
                            btn-flat blue accent-4 white-text"
                           href="{% url 'record_to_course' pk=course.pk %}">Запись</a>
                    {% endif %}
                </div>
            </div>
            <div class="header-problem">
                <h4>{{ course.title }}</h4>
            </div>
            <ul>
                <li>Цена: {{ course.price }}</li>
                <li>Дата начала: {{ course.start_date }} </li>
                <li>Продолжительность: {{ course.duration }}
                <li>Преподователь: <a href="{% url 'profile' username=course.lecturer %}">
                    {% firstof course.lecturer.get_full_name course.lecturer.get_username %}</a></li>
                {% if course.contract and course.invoice %}
                    <li><a href="{{ course.contract.url }}" target="_blank">Договор на оказание услуг</a></li>
                    <li><a href="{{ course.invoice.url }}" target="_blank">Квитанция на оплату услуг</a></li>
                {% elif course.contract %}
                    <li><a href="{{ course.contract.url }}" target="_blank">Договор на оказание услуг</a></li>
                    <li>Преподователь не загрузил квитанцию. Обратитесь к нему лично.</li>
                {% elif course.invoice %}
                    <li><a href="{{ course.invoice.url }}" target="_blank">Квитанция на оплату услуг</a></li>
                    <li>Преподователь не загрузил договор. Обратитесь к нему лично.</li>
                {% else %}
                    <li>Преподователь не загрузил договор и квитанцию. Обратитесь к нему лично.</li>
                {% endif %}
                <li><a href="{{ course.work_program.url }}" target="_blank">Рабочая программа</a></li>
                <!-- Конец костыля. -->
            </ul>
        </div>
        <div class="col s12 l6">
            Записавшиеся на курс:

            <ul>
            <li>
            {%for record in records%}
            <a class="white-text author" href="{% url 'profile' username=record.student %}">
                <div class="author-photo small-photo rounded"
                     style="background-image: url(' {{ record.student.profile.image.url }} ')">
                </div>
                <div class="author-name black-text">
                    {% firstof record.student.get_full_name record.student.get_username %}
                </div>
            </a>
            {%empty%}
            Пока еще никто не записался.
            {%endfor%}
        </li>
        </ul>
        </div>
    </div>
{% endblock %}
{% block course_new %}
{% endblock %}

templates/course/course_edit.html
{% extends 'base.html' %}
{% block create_course %}
{% endblock %}
{% block course %}
    <div class="section">
        <h4 align="center">Новый курс</h4>
        <br>
        <div class="row">
            <form method="POST" enctype="multipart/form-data" class="col s12">
                <div class="row">
                    <div class="input-field col s12">
                        <i class="material-icons prefix">title</i>
                        {{ form.title }}
                        <label>Название:</label>
                    </div>
                    <div class="input-field col s12">
                        <i class="material-icons prefix">comment</i>
                        {{ form.description }}
                        <label>Описание:</label>
                    </div>
                    <div class="input-field col s6">
                        <i class="material-icons prefix">attach_money</i>
                        {{ form.price }}
                        <label>Цена:</label>
                        <span class="helper-text" data-error="wrong"
                              data-success="right">Стоимость указывается в рублях.</span>
                    </div>
                    <div class="input-field col s6">
                        <i class="material-icons prefix">date_range</i>
                        {{ form.start_date.as_widget }}
                        <label>Дата начала:</label>
                        <span class="helper-text" data-error="wrong"
                              data-success="right">Дата и время начала первого занятия.</span>
                    </div>
                    <div class="input-field col s6">
                        <i class="material-icons prefix">assignment</i>
                        {{ form.duration }}
                        <label>Колличество занятий:</label>
                        <span class="helper-text" data-error="wrong"
                              data-success="right">Общее количество занятий.</span>
                    </div>
                    <div class="input-field col s6">
                        <i class="material-icons prefix">av_timer</i>
                        {{ form.lesson_duration }}
                        <label>Продолжительность одного занятия:</label>
                        <span class="helper-text" data-error="wrong" data-success="right">Указывать в академических часах(1 час = 45 мин).</span>
                    </div>



                    <div class="file-field input-field col s12">
                        <div class="btn blue darken-4">
                            <span>Обложка:</span>
                            {{ form.image }}
                        </div>
                        <div class="file-path-wrapper">
                            <input class="file-path validate" type="text" placeholder="Загрузите обложку для вашего курса">
                        </div>
                    </div>
                    <div class="file-field input-field col s12">
                        <div class="btn blue darken-4">
                            <span>Договор:</span>
                            {{ form.contract }}
                        </div>
                        <div class="file-path-wrapper">

                            <input class="file-path validate" type="text" placeholder="Загрузите договор для вашего курса">
                        </div>
                    </div>
                    <div class="file-field input-field col s12">
                        <div class="btn blue darken-4">
                            <span>Квитанция:</span>
                            {{ form.invoice }}
                        </div>
                        <div class="file-path-wrapper">

                            <input class="file-path validate" type="text" placeholder="Загрузите квитанцию для вашего курса">
                        </div>
                    </div>
                    <div class="file-field input-field col s12">
                        <div class="btn blue darken-4">
                            <span>Рабочая программа:</span>
                            {{ form.work_program }}
                        </div>
                        <div class="file-path-wrapper">

                            <input class="file-path validate" type="text" placeholder="Загрузите рабочую программу вашего курса">
                        </div>
                    </div>
                </div>
                {% csrf_token %}
                <button class="btn waves-effect waves-light right blue darken-4" type="submit" name="action">
                    Сохранить
                    <i class="material-icons right">send</i>
                </button>

            </form>
        </div>
    </div>
{% endblock %}
{% block course_new %}
{% endblock %}

templates/course/course_list.html
{% extends 'base.html' %}

{% block course %}
    <h2>Список курсов</h2>
    <div class="row">
        {% for course in course %}
            <div class="col s12 m6 l6">
                <div class="card z-depth-2
                {% if request.user == course.lecturer %}
                                grey lighten-1 lecturer" data-desc="Цена: {{ course.price }}">
                {% else %}
                    green lighten-1 new" data-desc="Цена: {{ course.price }}">
                {% endif %}
                <div class="card-content white-text">
                    <span class="card-title">{{ course.title }}</span>
                    <p>{{ course.description|linebreaksbr }}</p>
                </div>
                <div class="card-action">
                    <a class="white-text
                    {% if request.user == course.lecturer %}
                                grey lighten-2
                    {% else %}
                    green lighten-2
                    {% endif %}
                    btn btn-flat waves waves-effect"
                       href="{% url 'course_detail' pk=course.pk %}">Подробно</a>
                    <span class="white-text card-date"> {{ course.start_date }} </span>
                    <a class="white-text author" href="{% url 'profile' username=course.lecturer %}">
                        <div class="author-photo small-photo rounded"
                             style="background-image: url(' {{ course.lecturer.profile.image.url }} ')">
                        </div>
                        <div class="author-name">
                            {% firstof course.lecturer.get_full_name course.lecturer.get_username %}
                        </div>
                    </a>
                </div>
                </div>
            </div>
        {% endfor %}
    </div>
    {% include "pagination.html" with page=course %}
{% endblock %}

templates/course/my_course.html
{% extends 'base.html' %}
{% block course %}
    <h2>Список курсов</h2>
    <div class="row">
        {% for my_course in my_course %}
            <div class="col s12 m6 l6">
                <div class="card z-depth-2
                 {% if request.user == my_course.lecturer %}
                     grey lighten-1 lecturer" data-desc="Цена: {{ my_course.price }}">
                {% else %}
                    green lighten-1 new" data-desc="Цена: {{ my_course.price }}">
                {% endif %}
                <div class="card-content white-text">
                    <span class="card-title">{{ my_course.title }}</span>
                    <p>{{ my_course.description|linebreaksbr }}</p>
                </div>
                <div class="card-action">
                    <a class="white-text
                    {% if request.user == my_course.lecturer %}
                                grey lighten-2
                    {% else %}
                    green lighten-2
                    {% endif %}
                    btn btn-flat waves waves-effect"
                       href="{% url 'course_detail' pk=my_course.pk %}">Подробно</a>
                    <span class="white-text card-date"> {{ my_course.start_date }} </span>
                    <a class="white-text author" href="{% url 'profile' username=my_course.lecturer %}">
                        <div class="author-photo small-photo rounded"
                             style="background-image: url(' {{ my_course.lecturer.profile.image.url }} ')">
                        </div>
                        <div class="author-name">
                            {% firstof my_course.lecturer.get_full_name my_course.lecturer.get_username %}
                        </div>
                    </a>
                </div>
                </div>
            </div>
        {% endfor %}
    </div>
    {% include "pagination.html" with page=my_course %}
{% endblock %}

templates/course/record_to_course.html
{% extends 'base.html' %}

{% block course %}
    <div class="section">
        <h4 align="center">Запись на курс</h4>
        <br>
        <div class="row">
            <form method="POST" enctype="multipart/form-data" class="col s12">
                <div class="row">
                    <div class="input-field col s6">
                        <i class="material-icons prefix">account_circle</i>
                        {{ form.name }}
                        <label>Имя:</label>
                    </div>
                    <div class="input-field col s6">
                        <i class="material-icons prefix">account_circle</i>
                        {{ form.surname }}
                        <label>Фамилия:</label>
                    </div>
                    <div class="input-field col s6">
                        <i class="material-icons prefix">account_circle</i>
                        {{ form.patronymic }}
                        <label for="id_patronymic">Отчество:</label>
                    </div>
                    <div class="input-field col s6">
                        <i class="material-icons prefix">date_range</i>
                        {{ form.date_birth.as_widget }}
                        <label for="id_date_birth">Дата рождения:</label>
                    </div>
                    <div class="input-field col s6">
                        <i class="material-icons prefix">smartphone</i>
                        {{ form.phone }}
                        <label for="id_phone">Номер телефона:</label>
                    </div>
                    <div class="input-field col s6">
                        <i class="material-icons prefix">contact_mail</i>
                        {{ form.email }}
                        <label for="id_email">Адрес электронной почты:</label>
                    </div>
                    <div class="input-field col s12">
                        {{ form.institute }}
                    </div>
                    <div class="input-field col s12">
                        {{ form.department }}
                    </div>
                    <div class="input-field col s12">
                        {{ form.group }}
                    </div>

                    <div class="file-field input-field col s12">
                        <div class="btn blue darken-4">
                            <span>Договор</span>
                            {{ form.contract }}
                        </div>
                        <div class="file-path-wrapper">
                            <input class="file-path validate" type="text" placeholder="Загрузите подписанный договор">
                        </div>
                    </div>
                    <div class="file-field input-field col s12">
                        <div class="btn blue darken-4">
                            <span>Квитанция</span>
                            {{ form.invoice }}
                        </div>
                        <div class="file-path-wrapper">
                            <input class="file-path validate" type="text" placeholder="Загрузите оплаченую квитанцию">
                        </div>
                    </div>
                </div>
                    {% csrf_token %}
                    <button class="btn waves-effect waves-light right blue darken-4" type="submit" name="action">
                        Сохранить
                        <i class="material-icons right">send</i>
                    </button>
            </form>
        </div>
    </div>

{% endblock %}